### ISSUE TITLE
Add global delay after input events

### ISSUE THREAD

**Issue by jusw85** [peoro/ngu.js#4]
It might be helpful to slowdown the automation by adding a slight delay after each input event e.g. keypress, mouseclick so that it's easier to track the automation on screen.

**Comment by peoro** [comment]
Currently the scheduling algorithm for input events sends one event allows exactly one sequence of events each frame.  
"Sequence of events" means that multiple events can be sent at the same frame, if that doesn't change the way NGU processes them. (The details are described in [`src/io.js:9-30`](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/io.js#L9-L30))

In order to delay the input, the code waits for `ngujs.io.toState( next_input_type )` before triggering new events.  
That function waits for all the events scheduled so far, and optionally for the next game frame if the new event can't be added to the latest sequence of events. This logic is handled by `IO.State` at [`src/io.js:87-134`](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/io.js#L87-L134).

We should be able to add a delay after each event by adding an `await io.nextFrame;` or `await wait( time_in_secs )` around line [110](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/io.js#L110) (`wait()` is from [`src/utils.js`](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/util.js#L93)).  
Instead, to add a delay after each sequence of events, the `await` statement above should be after line [108](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/io.js#L108).

I would put the delay amount in a configurable parameter, and would run no extra `await` if the parameter is set to 0.

There are some unit tests for the event scheduler in [`tests/io.js`](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/tests/io.js#L8-L152), since it's a tricky and very important piece of logic. Please make sure that the tests keep passing after touching that file. It would be awesome to add a test for the delay as well, to make sure that it works correctly.
